### ISSUE TITLE
Issue to run migaration

### ISSUE THREAD

**Issue by aoonuos2013** [ant-vel/Shop#1]
Hi Sir 
I am trying to run this project on my localhost server but its not work correctly i have solve many issues but at the end when i run the migration it show this error in my browser please guide me or upload the database file of this project...thanks

**Comment by gocanto** [comment]
can you post the issue?

**Comment by aoonuos2013** [comment]
Yes Sir I have some problem in migrations when I run migration of this
command "php artisan migrate" it through error like this..error image
attach inside the mail.

[image: Inline image 1]

[image: Inline image 2]

Profound Regards
*Aoon Raza*
*03157628577*

**Comment by gocanto** [comment]
I am not able to see the posted pics.. can you please, resend them back up

**Comment by aoonuos2013** [comment]
Sure Sir I attach again the pics inside the mail please check it and guide
me how to solve this issue

Profound Regards
*Aoon Raza*
*03157628577*

**Comment by gocanto** [comment]
Dont see the pictures yet

**Comment by aoonuos2013** [comment]
Sir Are you have a Skype id or whatsapp or other communication meadia if
yes then send me you id or send me your gmail,outlook  or yahoo email
address.


Profound Regards
*Aoon Raza*
*03157628577*

**Comment by gocanto** [comment]
where is this happening?

**Comment by gocanto** [comment]
give me your email to add you to slack

**Comment by aoonuos2013** [comment]
Sir this is my gmail account: aoonuos2013@gmail.com
Skype ID: aoonuos74
Phone No: +923157628577

Profound Regards
*Aoon Raza*
*03157628577*

**Comment by gocanto** [comment]
I sent you the slack invitation.
